from __future__ import annotations

import json
import logging
import os
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import requests
from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel, Field

from app.config import ENV_FILE

logger = logging.getLogger("job_ops.local_llm")


class ChatMessage(BaseModel):
    role: str
    content: str | list[dict[str, Any]] | None = None


class ChatCompletionsRequest(BaseModel):
    model: str = "qwen2.5:1.5b-instruct"
    temperature: float = 0.2
    response_format: dict[str, Any] | None = None
    messages: list[ChatMessage] = Field(default_factory=list)


@dataclass
class ParsedPrompt:
    user_prompt: str
    jd_name: str
    job_context: str
    guide: str
    master_cv: str
    jd_text: str


SECTION_ORDER = ["USER_PROMPT", "JD_FILE_NAME", "JOB_CONTEXT", "GUIDE", "MASTER_CV", "JD_DB_TEXT", "JD_TEXT"]


def _extract_plain_content(msg: ChatMessage) -> str:
    if isinstance(msg.content, str):
        return msg.content
    if isinstance(msg.content, list):
        chunks: list[str] = []
        for item in msg.content:
            if isinstance(item, dict) and "text" in item:
                chunks.append(str(item.get("text", "")))
        return "\n".join(chunks)
    return ""


def _parse_sections(text: str) -> ParsedPrompt:
    text = str(text or "")
    indices: list[tuple[str, int]] = []
    for name in SECTION_ORDER:
        marker = f"{name}:\n"
        idx = text.find(marker)
        if idx >= 0:
            indices.append((name, idx))
    indices.sort(key=lambda x: x[1])

    values: dict[str, str] = {k: "" for k in SECTION_ORDER}
    for i, (name, start_idx) in enumerate(indices):
        marker = f"{name}:\n"
        content_start = start_idx + len(marker)
        end_idx = indices[i + 1][1] if i + 1 < len(indices) else len(text)
        values[name] = text[content_start:end_idx].strip()

    return ParsedPrompt(
        user_prompt=values.get("USER_PROMPT", ""),
        jd_name=values.get("JD_FILE_NAME", ""),
        job_context=values.get("JOB_CONTEXT", ""),
        guide=values.get("GUIDE", ""),
        master_cv=values.get("MASTER_CV", ""),
        jd_text=values.get("JD_DB_TEXT", "") or values.get("JD_TEXT", ""),
    )


def _extract_title_company(job_context: str) -> tuple[str, str]:
    try:
        obj = json.loads(job_context or "{}")
        title = str(obj.get("title") or "").strip()
        company = str(obj.get("company") or "").strip()
        return title, company
    except Exception as exc:
        logger.warning("Failed to parse JOB_CONTEXT JSON | error=%s", str(exc))
        return "", ""


def _compose_cover_letter(title: str, company: str) -> str:
    target = title or "the role"
    at_company = f" at {company}" if company else ""
    return (
        f"Dear Hiring Team{at_company},\n\n"
        f"I am excited to apply for {target}. I bring hands-on full-stack delivery experience across "
        "frontend, backend APIs, and production support.\n\n"
        "I focus on pragmatic implementation, measurable outcomes, and maintainable software quality.\n\n"
        "Thank you for your time and consideration.\n"
    )


def _compose_cv(master_cv: str, title: str) -> str:
    base = (master_cv or "").strip()
    if not base:
        return "<bold><center>CV Output</center></bold>\n<bold><green>Professional Summary</green></bold>\n- Generated by local fallback LLM server.\n"
    if title:
        lines = base.splitlines()
        rebuilt: list[str] = []
        replaced = False
        for line in lines:
            stripped = line.strip()
            if not replaced and stripped.startswith("<center>") and stripped.endswith("</center>") and "|" not in stripped:
                rebuilt.append(f"<center>{title}</center>")
                replaced = True
            else:
                rebuilt.append(line)
        return "\n".join(rebuilt).strip() + "\n"
    return base + "\n"


def _extract_responses_output_text(data: dict[str, Any]) -> str:
    direct = str(data.get("output_text") or "").strip()
    if direct:
        return direct
    chunks: list[str] = []
    for item in data.get("output", []) or []:
        if item.get("type") != "message":
            continue
        for content in item.get("content", []) or []:
            text_value = str(content.get("text") or "").strip()
            if text_value:
                chunks.append(text_value)
    return "\n".join(chunks).strip()


def _read_env_file_value(name: str) -> str:
    if not ENV_FILE.exists():
        return ""
    try:
        for line in ENV_FILE.read_text(encoding="utf-8", errors="ignore").splitlines():
            raw = line.strip()
            if not raw or raw.startswith("#") or "=" not in raw:
                continue
            key, value = raw.split("=", 1)
            if key.strip() == name:
                return value.strip().strip("'").strip('"')
    except Exception as exc:
        logger.warning("Failed reading .env for %s: %s", name, exc)
    return ""


def _resolve_env_value(name: str) -> str:
    return str(os.getenv(name, "") or "").strip() or _read_env_file_value(name)


def _resolve_internal_token() -> str:
    return _resolve_env_value("INTERNAL_LLM_SHARED_TOKEN")


def _resolve_upstream_provider() -> str:
    return (_resolve_env_value("LLM_UPSTREAM_PROVIDER") or "ollama").strip().lower()


def _resolve_upstream_base_url() -> str:
    return (
        _resolve_env_value("LLM_UPSTREAM_BASE_URL")
        or _resolve_env_value("OLLAMA_BASE_URL")
        or "http://127.0.0.1:11434"
    ).rstrip("/")


def _resolve_upstream_model(requested_model: str) -> str:
    configured = (
        _resolve_env_value("LLM_UPSTREAM_MODEL")
        or _resolve_env_value("OLLAMA_MODEL")
        or "qwen2.5:1.5b-instruct"
    ).strip()
    candidate = str(requested_model or "").strip()
    if candidate:
        normalized = candidate.lower()
        if normalized.startswith(("gpt-", "o1", "o3", "o4", "claude", "gemini")):
            return configured
        return candidate
    return configured


def _build_chat_response(*, model: str, content: str, usage: dict[str, Any]) -> dict[str, Any]:
    now = int(datetime.now(timezone.utc).timestamp())
    return {
        "id": f"chatcmpl-local-{uuid.uuid4().hex[:16]}",
        "object": "chat.completion",
        "created": now,
        "model": model or "local-cv-rewriter",
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": "stop",
            }
        ],
        "usage": usage,
    }


def _build_fallback_response(*, parsed: ParsedPrompt, model: str, reason: str) -> dict[str, Any]:
    title, company = _extract_title_company(parsed.job_context)
    response_obj = {
        "cv_text": _compose_cv(parsed.master_cv, title=title),
        "cover_letter": _compose_cover_letter(title=title, company=company),
        "notes": [
            "Generated by embedded local fallback LLM (heuristic mode).",
            f"Fallback reason: {reason}.",
        ],
    }
    content = json.dumps(response_obj, ensure_ascii=False)
    merged = "\n\n".join(part for part in [parsed.user_prompt, parsed.guide, parsed.master_cv, parsed.jd_text] if part)
    usage = {
        "prompt_tokens": max(1, len(merged) // 4),
        "completion_tokens": max(1, len(content) // 4),
        "total_tokens": max(2, (len(merged) + len(content)) // 4),
        "fallback": True,
        "fallback_reason": reason,
        "llm_backend": "gateway_fallback_heuristic",
        "gateway_authenticated": bool(_resolve_internal_token()),
    }
    return _build_chat_response(model=model, content=content, usage=usage)


def _call_ollama_chat_upstream(
    *,
    model: str,
    temperature: float,
    system_prompt: str,
    user_content: str,
) -> tuple[str, dict[str, Any], str]:
    base_url = _resolve_upstream_base_url()
    provider = _resolve_upstream_provider()
    if provider != "ollama":
        raise ValueError(f"unsupported_upstream_provider:{provider or 'unknown'}")
    resolved_model = _resolve_upstream_model(model)
    messages: list[dict[str, str]] = []
    if system_prompt.strip():
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": user_content})
    payload: dict[str, Any] = {
        "model": resolved_model,
        "messages": messages,
        "stream": False,
        "format": {
            "type": "object",
            "properties": {
                "headline": {"type": "string"},
                "summary": {"type": "string"},
                "notes": {
                    "type": "array",
                    "items": {"type": "string"},
                },
            },
            "required": ["headline", "summary"],
        },
        "options": {
            "temperature": max(0.05, min(0.3, float(temperature))),
            "num_predict": 320,
            "num_ctx": 1536,
            "num_thread": max(2, min(4, int(os.cpu_count() or 2))),
            "top_k": 20,
            "top_p": 0.9,
            "repeat_penalty": 1.05,
        },
        "keep_alive": "30m",
    }
    resp = requests.post(
        f"{base_url}/api/chat",
        headers={"Content-Type": "application/json"},
        json=payload,
        timeout=900,
    )
    if resp.status_code >= 400:
        raise ValueError(f"ollama_status_{resp.status_code}")
    data = resp.json()
    content = str(((data.get("message") or {}).get("content")) or "").strip()
    if not content:
        raise ValueError("empty_ollama_output")
    usage = {
        "prompt_eval_count": data.get("prompt_eval_count"),
        "eval_count": data.get("eval_count"),
        "total_duration": data.get("total_duration"),
        "load_duration": data.get("load_duration"),
        "prompt_eval_duration": data.get("prompt_eval_duration"),
        "eval_duration": data.get("eval_duration"),
    }
    usage["fallback"] = False
    usage["llm_backend"] = "gateway_ollama_chat"
    usage["upstream_base_url"] = base_url
    usage["upstream_provider"] = provider
    usage["upstream_model"] = resolved_model
    return content, usage, resolved_model


def process_chat_completions_request(
    payload: ChatCompletionsRequest,
    *,
    authorization: str | None = None,
    x_internal_llm_token: str | None = None,
) -> dict[str, Any]:
    required_token = _resolve_internal_token()
    if required_token:
        bearer = ""
        if str(authorization or "").lower().startswith("bearer "):
            bearer = str(authorization or "")[7:].strip()
        provided = x_internal_llm_token or bearer
        if provided != required_token:
            raise HTTPException(status_code=401, detail="Invalid internal LLM token")
    logger.info(
        "Chat completion request | model=%s temperature=%s messages=%s",
        payload.model,
        payload.temperature,
        len(payload.messages or []),
    )
    user_messages = [m for m in payload.messages if (m.role or "").lower() == "user"]
    merged = "\n\n".join(_extract_plain_content(m) for m in user_messages)
    logger.info(
        "Chat completion prompt parsed | user_messages=%s merged_chars=%s",
        len(user_messages),
        len(merged),
    )
    parsed = _parse_sections(merged)
    title, company = _extract_title_company(parsed.job_context)
    logger.info(
        "Chat completion context | jd_name=%s title=%s company=%s master_cv_chars=%s jd_chars=%s guide_chars=%s",
        parsed.jd_name,
        title[:120],
        company[:120],
        len(parsed.master_cv or ""),
        len(parsed.jd_text or ""),
        len(parsed.guide or ""),
    )

    system_messages = [m for m in payload.messages if (m.role or "").lower() == "system"]
    system_prompt = "\n\n".join(_extract_plain_content(m) for m in system_messages).strip()
    requested_model = payload.model or _resolve_upstream_model("")
    try:
        content, usage, resolved_model = _call_ollama_chat_upstream(
            model=requested_model,
            temperature=float(payload.temperature or 0.2),
            system_prompt=system_prompt,
            user_content=merged,
        )
        usage["gateway_authenticated"] = bool(required_token)
        logger.info(
            "Chat completion upstream success | model=%s content_chars=%s usage=%s",
            resolved_model,
            len(content),
            usage,
        )
        return _build_chat_response(
            model=resolved_model,
            content=content,
            usage=usage,
        )
    except Exception as exc:
        reason = str(exc) or "gateway_fallback"
        logger.warning("Chat completion upstream fallback | reason=%s", reason)
        response = _build_fallback_response(
            parsed=parsed,
            model=payload.model or "local-cv-rewriter",
            reason=reason,
        )
        logger.info(
            "Chat completion response ready | model=%s content_chars=%s usage=%s",
            payload.model or "local-cv-rewriter",
            len(response["choices"][0]["message"]["content"]),
            response["usage"],
        )
        return response


def build_local_llm_router() -> APIRouter:
    router = APIRouter(prefix="/v1", tags=["local-llm"])

    @router.get("/health")
    def health() -> dict[str, Any]:
        now = datetime.now(timezone.utc).isoformat()
        logger.info("Health check | endpoint=/v1/health time=%s", now)
        return {
            "status": "ok",
            "name": "local-llm-gateway",
            "time": now,
            "upstream_provider": _resolve_upstream_provider(),
            "upstream_base_url": _resolve_upstream_base_url(),
            "default_model": _resolve_upstream_model(""),
        }

    @router.post("/chat/completions")
    def chat_completions(
        payload: ChatCompletionsRequest,
        authorization: str | None = Header(default=None),
        x_internal_llm_token: str | None = Header(default=None, alias="X-Internal-LLM-Token"),
    ) -> dict[str, Any]:
        return process_chat_completions_request(
            payload,
            authorization=authorization,
            x_internal_llm_token=x_internal_llm_token,
        )

    return router
