from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel, Field


app = FastAPI(title="Job Ops Local LLM", version="1.0.0")


class ChatMessage(BaseModel):
    role: str
    content: str | list[dict[str, Any]] | None = None


class ChatCompletionsRequest(BaseModel):
    model: str = "local-cv-rewriter"
    temperature: float = 0.2
    response_format: dict[str, Any] | None = None
    messages: list[ChatMessage] = Field(default_factory=list)


@dataclass
class ParsedPrompt:
    user_prompt: str
    jd_name: str
    job_context: str
    guide: str
    master_cv: str
    jd_text: str


SECTION_ORDER = ["USER_PROMPT", "JD_FILE_NAME", "JOB_CONTEXT", "GUIDE", "MASTER_CV", "JD_DB_TEXT", "JD_TEXT"]


def _extract_plain_content(msg: ChatMessage) -> str:
    if isinstance(msg.content, str):
        return msg.content
    if isinstance(msg.content, list):
        chunks: list[str] = []
        for item in msg.content:
            if isinstance(item, dict) and "text" in item:
                chunks.append(str(item.get("text", "")))
        return "\n".join(chunks)
    return ""


def _parse_sections(text: str) -> ParsedPrompt:
    text = str(text or "")
    indices: list[tuple[str, int]] = []
    for name in SECTION_ORDER:
        marker = f"{name}:\n"
        idx = text.find(marker)
        if idx >= 0:
            indices.append((name, idx))
    indices.sort(key=lambda x: x[1])

    values: dict[str, str] = {k: "" for k in SECTION_ORDER}
    for i, (name, start_idx) in enumerate(indices):
        marker = f"{name}:\n"
        content_start = start_idx + len(marker)
        end_idx = indices[i + 1][1] if i + 1 < len(indices) else len(text)
        values[name] = text[content_start:end_idx].strip()

    return ParsedPrompt(
        user_prompt=values.get("USER_PROMPT", ""),
        jd_name=values.get("JD_FILE_NAME", ""),
        job_context=values.get("JOB_CONTEXT", ""),
        guide=values.get("GUIDE", ""),
        master_cv=values.get("MASTER_CV", ""),
        jd_text=values.get("JD_DB_TEXT", "") or values.get("JD_TEXT", ""),
    )


def _extract_title_company(job_context: str) -> tuple[str, str]:
    try:
        obj = json.loads(job_context or "{}")
        title = str(obj.get("title") or "").strip()
        company = str(obj.get("company") or "").strip()
        return title, company
    except Exception:
        return "", ""


def _compose_cover_letter(title: str, company: str) -> str:
    target = title or "the role"
    at_company = f" at {company}" if company else ""
    return (
        f"Dear Hiring Team{at_company},\n\n"
        f"I am excited to apply for {target}. I bring hands-on full-stack delivery experience across "
        "frontend, backend APIs, and production support. I focus on practical engineering outcomes, "
        "clear communication, and maintainable implementation.\n\n"
        "In my recent work, I have built and supported production features end-to-end: translating requirements, "
        "implementing reliable services, and collaborating across teams to ship quality software.\n\n"
        "Thank you for your time and consideration.\n"
    )


def _compose_cv(master_cv: str, title: str) -> str:
    base = (master_cv or "").strip()
    if not base:
        return "<bold><center>CV Output</center></bold>\n<bold><green>Professional Summary</green></bold>\n- Generated by local fallback LLM server.\n"

    if title:
        lines = base.splitlines()
        rebuilt: list[str] = []
        replaced = False
        for line in lines:
            stripped = line.strip()
            if not replaced and stripped.startswith("<center>") and stripped.endswith("</center>") and "|" not in stripped:
                rebuilt.append(f"<center>{title}</center>")
                replaced = True
            else:
                rebuilt.append(line)
        return "\n".join(rebuilt).strip() + "\n"
    return base + "\n"


@app.get("/health")
def health() -> dict[str, Any]:
    return {"status": "ok", "name": "local-llm", "time": datetime.now(timezone.utc).isoformat()}


@app.post("/v1/chat/completions")
def chat_completions(payload: ChatCompletionsRequest) -> dict[str, Any]:
    user_messages = [m for m in payload.messages if (m.role or "").lower() == "user"]
    merged = "\n\n".join(_extract_plain_content(m) for m in user_messages)
    parsed = _parse_sections(merged)
    title, company = _extract_title_company(parsed.job_context)

    response_obj = {
        "cv_text": _compose_cv(parsed.master_cv, title=title),
        "cover_letter": _compose_cover_letter(title=title, company=company),
        "notes": [
            "Generated by local fallback LLM server (heuristic mode).",
            "No external model/API key used.",
            "MASTER_CV reused and lightly aligned with JOB_CONTEXT title.",
        ],
    }
    content = json.dumps(response_obj, ensure_ascii=False)
    now = int(datetime.now(timezone.utc).timestamp())
    return {
        "id": f"chatcmpl-local-{uuid.uuid4().hex[:16]}",
        "object": "chat.completion",
        "created": now,
        "model": payload.model or "local-cv-rewriter",
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": "stop",
            }
        ],
        "usage": {
            "prompt_tokens": max(1, len(merged) // 4),
            "completion_tokens": max(1, len(content) // 4),
            "total_tokens": max(2, (len(merged) + len(content)) // 4),
        },
    }
